maxDepth: 5
concurrency: 10
boltDBPath: "data/mydb.db"
redisAddress: "localhost:6379"
filterDomain: "https://www.webscraper.io/test-sites/e-commerce/allinone-popup-links/phones"
exampleQueryLink: "https://www.webscraper.io/test-sites/e-commerce/allinone-popup-links/phones"